# Generated by Django 5.2.5 on 2025-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_signupevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
