# Generated by Django 5.2.5 on 2025-10-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_signupevent_latitude_signupevent_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupevent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='signupevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='signupevent',
            name='longitude',
        ),
        migrations.AddField(
            model_name='signupevent',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupevent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
