# Generated by Django 5.2.5 on 2025-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_order_order_id_order_payment_method_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('spud', 'Spud'), ('appetizers', 'Appetizers'), ('wrap', 'Wrap'), ('pasta_bread', 'Pasta/Bread'), ('desserts', 'Desserts')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
