# Generated by Django 5.2.5 on 2025-11-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_product_category_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
