# Generated by Django 5.2.5 on 2025-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_product_size_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('hero_button_text', 'Hero Button Text'), ('hero_image', 'Hero Image'), ('featured_section_title', 'Featured Section Title'), ('about_us_title', 'About Us Title'), ('about_us_content', 'About Us Content'), ('footer_address', 'Footer Address'), ('footer_email', 'Footer Email'), ('footer_facebook_url', 'Footer Facebook URL'), ('footer_instagram_url', 'Footer Instagram URL'), ('featured_item_1', 'Featured Item 1'), ('featured_item_2', 'Featured Item 2'), ('featured_item_3', 'Featured Item 3'), ('featured_item_4', 'Featured Item 4')], max_length=50, unique=True)),
                ('content', models.TextField(blank=True, help_text='Text content or image URL')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order for sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frontend Content',
                'verbose_name_plural': 'Frontend Content',
                'ordering': ('order', 'section_key'),
            },
        ),
    ]
