# Generated by Django 5.2.5 on 2025-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_frontendcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for order notifications', max_length=254, null=True),
        ),
    ]
